### ISSUE TITLE
Robot_Toolkit: Issue with pushing gravity loads with named groups

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Robot_Toolkit#125]
Trying to push gravity loads for all bars.Potential source of error: The gravity loads BHoM component will only accept a group of BHoMObjects not Bars, thus when pushed to Robot it is unable to assign the object correctly. Error message '1. Solution exception:Object reference not set to an instance of an object.'

**Comment by IsakNaslundBh** [comment]
Problem here seem to be coming from putting a name on the group:

![image](https://user-images.githubusercontent.com/22005920/52870249-b1fb8280-3147-11e9-91b5-1c18662aa057.png)

Doing this, the adapter tries to find a predefined group in Robot rather than using the objects, and as there was no group named like this, it crashes, which is a bug that needs to be fixed, but less severe.

Using the gravity load comp that takes a IEnumerable instead of a group, or not naming the group, things seem to be working as expected.
![image](https://user-images.githubusercontent.com/22005920/52870318-dd7e6d00-3147-11e9-9b15-043b2853e0d3.png)

**Comment by IsakNaslundBh** [comment]
This can be tackled together with https://github.com/BHoM/Robot_Toolkit/issues/238 as both relates to pushing of gravity loads
